# Generated by Django 3.1 on 2020-08-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_agentmodel_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentmodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
