# Generated by Django 3.0.8 on 2020-08-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housemodel',
            name='build',
        ),
        migrations.RemoveField(
            model_name='housemodel',
            name='sqft',
        ),
        migrations.AddField(
            model_name='housemodel',
            name='area',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='housemodel',
            name='area_ground',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='housemodel',
            name='build_year',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='housemodel',
            name='floors',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='housemodel',
            name='home_type',
            field=models.CharField(choices=[('APARTMENT', 'Apartment'), ('VILLA', 'Villa'), ('TERRACED_HOUSE', 'Terraced house'), ('FARM_HOUSE', 'Farm house'), ('MANSION', 'Mansion')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='housemodel',
            name='address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='housemodel',
            name='bedrooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='housemodel',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='housemodel',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='housemodel',
            name='zipcode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
