# Generated by Django 3.0.8 on 2020-08-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_auto_20200820_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='housemodel',
            name='rooms',
            field=models.IntegerField(null=True),
        ),
    ]
