# Generated by Django 3.0.8 on 2020-08-06 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_auto_20200806_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingmodel',
            name='sale_type',
        ),
    ]
