# Generated by Django 3.0.8 on 2020-08-06 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_remove_listingmodel_sale_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingmodel',
            name='listed_date',
        ),
    ]
