# Generated by Django 3.0.8 on 2020-08-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_remove_listingmodel_listed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingmodel',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='home_type',
            field=models.CharField(choices=[('APARTMENT', 'Apartment'), ('VILLA', 'Villa'), ('TERRACED_HOUSE', 'Terraced house'), ('FARM_HOUSE', 'Farm house'), ('MANSION', 'Mansion')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='image_10',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='image_6',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='image_7',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='image_8',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='image_9',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='listed_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='open_house',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='sale_type',
            field=models.CharField(choices=[('FOR_SALE', 'For Sale'), ('FOR_RENT', 'For Rent')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='slug',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
