# Generated by Django 3.0.8 on 2020-08-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0005_auto_20200806_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingmodel',
            name='home_type',
        ),
        migrations.RemoveField(
            model_name='listingmodel',
            name='open_house',
        ),
        migrations.AlterField(
            model_name='listingmodel',
            name='sale_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
