# Generated by Django 3.0.8 on 2020-08-20 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0007_auto_20200820_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('zipcode', models.CharField(max_length=100, null=True)),
                ('rooms', models.IntegerField(null=True)),
                ('bedrooms', models.IntegerField(null=True)),
                ('bathrooms', models.DecimalField(decimal_places=2, max_digits=5)),
                ('area', models.IntegerField(null=True)),
                ('area_ground', models.IntegerField(null=True)),
                ('floors', models.IntegerField(null=True)),
                ('build_year', models.DateTimeField(null=True)),
                ('home_type', models.CharField(choices=[('APARTMENT', 'Apartment'), ('VILLA', 'Villa'), ('TERRACED_HOUSE', 'Terraced house'), ('FARM_HOUSE', 'Farm house'), ('MANSION', 'Mansion')], max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listing.HouseModel'),
        ),
    ]
