# Generated by Django 3.0.8 on 2020-08-21 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0008_auto_20200820_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingmodel',
            name='open_house',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listingmodel',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house', to='listing.HouseModel'),
        ),
    ]
