# Generated by Django 3.0.8 on 2020-08-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0010_auto_20200824_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housemodel',
            name='bathrooms',
            field=models.IntegerField(null=True),
        ),
    ]
