# Generated by Django 3.0.8 on 2020-08-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0012_auto_20200825_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingmodel',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='Images'),
        ),
    ]
