# Generated by Django 3.0.8 on 2020-08-26 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_auto_20200825_1334'),
        ('listing', '0013_auto_20200826_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingmodel',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='agent.AgentModel'),
        ),
    ]
